name: smart_estate_mobile
description: "SmartEstate - A mobile-first estate management system for Kenyan residential estates"

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter

  # UI & Navigation
  cupertino_icons: ^1.0.8
  
  # State Management
  provider: ^6.1.2
  
  # Navigation
  go_router: ^14.2.7
  
  # Network & API
  http: ^1.2.2
  dio: ^5.4.3+1
  
  # Storage
  shared_preferences: ^2.3.2
  
  # Image & Media
  image_picker: ^1.1.2
  cached_network_image: ^3.4.1
  
  # UI Components
  flutter_svg: ^2.0.10+1
  
  # Forms & Validation
  form_field_validator: ^1.1.0
  
  # Date & Time
  intl: ^0.19.0
  
  # Firebase (for backend)
  firebase_core: ^3.6.0
  firebase_auth: ^5.3.1
  cloud_firestore: ^5.4.4
  firebase_storage: ^12.3.2
  firebase_messaging: ^15.1.3
  
  # Notifications
  flutter_local_notifications: ^18.0.1
  
  # Permissions
  permission_handler: ^11.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  change_app_package_name: ^1.4.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/

  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter-Regular.ttf
        - asset: assets/fonts/Inter-Medium.ttf
          weight: 500
        - asset: assets/fonts/Inter-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Inter-Bold.ttf
          weight: 700

